# CodeBook 
Wearable computing data set - Data collected from the accelerometers from the Samsung Galaxy S smartphone.
This is a code book describing the variables, the data, and any transformations and work perfomed to clean it up.

## Data Source 

1. Dataset download url: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

2. Full dataset description: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 



## The dataset includes the following files:


- 'README.txt'

- 'features_info.txt': Shows information about the variables used on the feature vector.

- 'features.txt': List of all features.

- 'activity_labels.txt': Links the class labels with their activity name.

- 'train/X_train.txt': Training set.

- 'train/y_train.txt': Training labels.

- 'test/X_test.txt': Test set.

- 'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis. 

- 'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration. 

- 'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second. 

We have not included in our current analysis the following tables (including their equivalents for the test data set)

1. 'train/Inertial Signals/total_acc_x_train.txt'
2. 'train/Inertial Signals/body_acc_x_train.txt'
3. train/Inertial Signals/body_gyro_x_train.txt'

## Transformations and data manipulation 

* For both train and test data sets :
    + reading data, assinging correct labels for the column names
    + include subject and activity information (ids)
* Merging the two datasets by row
* Excluding all measurements that that do not contain mean and standard deviation measurements from the merged dataset 
* Assigning descriptive labels for each of the activity ids 
* Generating the tidy dataset with the average of each variable for each activity and each subject


