# Getting and Cleaning Data 
## Course project 

### Task: 
 * You should create one R script called run_analysis.R that does the following. 
    + Merges the training and the test sets to create one data set.
    + Extracts only the measurements on the mean and standard deviation for each measurement. 
    + Uses descriptive activity names to name the activities in the data set
    + Appropriately labels the data set with descriptive variable names. 
    + From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

### Script dependencies and working directory
* The script requires the `reshape2` and `data.table` packages
* The working directory is the root folder of the unzipped dataset `UCI HAR Dataset`. 
Keep the folders hierarchy as default 
* Add the script in your working directory
* Running the script:
`setwd(".../UCI HAR Dataset")` ; `source("run_analysis.R")`

### Output
* The script outputs `tidy_data.txt`, the clean independent daset with the average of each variable for each activity and each subject.
